### ISSUE TITLE
Get it running

### ISSUE THREAD

**Issue by knaku** [juju4/ansible-cuckoo-sandbox#1]
Hi

I've probably done something wrong or my lesser experience with ansible truly shines through, but how do I run this playbook correctly? 

If I try to run /tasks/main.yml I get an error complaining about "when" not being a valid attribute.

Running "ansible-galaxy install juju4.cuckoo_sandbox" seems to go fine except that it complains about "juju4.redhat-epel" not existing, which I guess it doesn't. Even though installing juju4.redhat-epel by itself works fine the dependency isn't handled correctly. I guess it might have something with the url for the git repo?

Anyway after telling ansible to ignore the errors it seems to have completed.
This is where I am quite lost, where are the virtualenv created? Shouldn't a user and home directory for cuckoo be created. Am I supposed to add along any variables in a playbook including the role? Any help is appreciated.

I've been using ubuntu 16.04 and ansible 2.0.

Thanks in advance

**Comment by juju4** [comment]
You can see a typical execution of the role through travis.
from README badges: https://travis-ci.org/juju4/ansible-cuckoo-sandbox/jobs/502461965
get-dependencies.sh will fetch correct dependencies with github. 
Galaxy has issues managing versions because of the switch to semantic versioning. you are probably fetching an older version and as result, depends on juju4.redhat-epel which is now juju4.redhat_epel.
Another potential issues, there are role dependencies which are now deprecated/unmaintained (kbrebanov.* roles). still running fine.

You can check default settings for user and path
https://github.com/juju4/ansible-cuckoo-sandbox/blob/devel/defaults/main.yml

As for anything but especially more security tools, I advise you to use latest software version (18.04LTS, ansible 2.7+)

**Comment by juju4** [comment]
Additional comments or closing?

**Comment by unknown-if** [comment]
I still don't understand, how to start the installation? Write down the steps, please.

**Comment by juju4** [comment]
Please don't mix issues and provide more details on your problem in a separate one.

On this role usage, look at README and .travis.yml or test/integration/default as examples
On cuckoo, look at upstream documentation on https://docs.cuckoosandbox.org/en/latest/
